name: Build

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_ENV: "prod"

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dialog-smart-alert-dist
          path: dist/
          retention-days: 14
